### ISSUE TITLE
panic and SIGSEGV when referencing nested elements that are not present

### ISSUE THREAD

**Issue by mbaynton** [oliveagle/jsonpath#5]
Given the following json
```
{
  "ref": "refs/heads/develop",
  "before": "3c7a885113813e000e3c55087c74a7afae769def",
  "after": "0000000000000000000000000000000000000000",
  "created": false,
  "deleted": true,
  "forced": false,
  "base_ref": null,
  "compare": "https://github.umn.edu/MSI-Puppet/persistent_systems_node_hieradata/compare/3c7a88511381...000000000000",
  "commits": [

  ],
  "head_commit": null,
  "repository": {
    "id": 39928,
    "name": "persistent_systems_node_hieradata",
    "full_name": "MSI-Puppet/persistent_systems_node_hieradata",
    "owner": {
      "name": "MSI-Puppet",
      "email": null,
      "login": "MSI-Puppet",
      "id": 10233,
      "avatar_url": "https://avatars.github.umn.edu/u/10233?",
      "gravatar_id": "",
      "url": "https://github.umn.edu/api/v3/users/MSI-Puppet",
      "html_url": "https://github.umn.edu/MSI-Puppet",
      "followers_url": "https://github.umn.edu/api/v3/users/MSI-Puppet/followers",
      "following_url": "https://github.umn.edu/api/v3/users/MSI-Puppet/following{/other_user}",
      "gists_url": "https://github.umn.edu/api/v3/users/MSI-Puppet/gists{/gist_id}",
      "starred_url": "https://github.umn.edu/api/v3/users/MSI-Puppet/starred{/owner}{/repo}",
      "subscriptions_url": "https://github.umn.edu/api/v3/users/MSI-Puppet/subscriptions",
      "organizations_url": "https://github.umn.edu/api/v3/users/MSI-Puppet/orgs",
      "repos_url": "https://github.umn.edu/api/v3/users/MSI-Puppet/repos",
      "events_url": "https://github.umn.edu/api/v3/users/MSI-Puppet/events{/privacy}",
      "received_events_url": "https://github.umn.edu/api/v3/users/MSI-Puppet/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "private": true,
    "html_url": "https://github.umn.edu/MSI-Puppet/persistent_systems_node_hieradata",
    "description": "Node-specific hiera (e)yaml files for systems managed by ASO-PSI",
    "fork": false,
    "url": "https://github.umn.edu/MSI-Puppet/persistent_systems_node_hieradata",
    "forks_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/forks",
    "keys_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/keys{/key_id}",
    "collaborators_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/collaborators{/collaborator}",
    "teams_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/teams",
    "hooks_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/hooks",
    "issue_events_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/issues/events{/number}",
    "events_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/events",
    "assignees_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/assignees{/user}",
    "branches_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/branches{/branch}",
    "tags_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/tags",
    "blobs_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/git/blobs{/sha}",
    "git_tags_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/git/tags{/sha}",
    "git_refs_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/git/refs{/sha}",
    "trees_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/git/trees{/sha}",
    "statuses_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/statuses/{sha}",
    "languages_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/languages",
    "stargazers_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/stargazers",
    "contributors_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/contributors",
    "subscribers_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/subscribers",
    "subscription_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/subscription",
    "commits_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/commits{/sha}",
    "git_commits_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/git/commits{/sha}",
    "comments_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/comments{/number}",
    "issue_comment_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/issues/comments{/number}",
    "contents_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/contents/{+path}",
    "compare_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/compare/{base}...{head}",
    "merges_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/merges",
    "archive_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/{archive_format}{/ref}",
    "downloads_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/downloads",
    "issues_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/issues{/number}",
    "pulls_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/pulls{/number}",
    "milestones_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/milestones{/number}",
    "notifications_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/notifications{?since,all,participating}",
    "labels_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/labels{/name}",
    "releases_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/releases{/id}",
    "deployments_url": "https://github.umn.edu/api/v3/repos/MSI-Puppet/persistent_systems_node_hieradata/deployments",
    "created_at": 1514481400,
    "updated_at": "2018-01-19T20:29:29Z",
    "pushed_at": 1516395849,
    "git_url": "git://github.umn.edu/MSI-Puppet/persistent_systems_node_hieradata.git",
    "ssh_url": "git@github.umn.edu:MSI-Puppet/persistent_systems_node_hieradata.git",
    "clone_url": "https://github.umn.edu/MSI-Puppet/persistent_systems_node_hieradata.git",
    "svn_url": "https://github.umn.edu/MSI-Puppet/persistent_systems_node_hieradata",
    "homepage": "",
    "size": 7,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master",
    "stargazers": 0,
    "master_branch": "master",
    "organization": "MSI-Puppet"
  },
  "pusher": {
    "name": "bert0214",
    "email": "bert0214@umn.edu"
  },
  "organization": {
    "login": "MSI-Puppet",
    "id": 10233,
    "url": "https://github.umn.edu/api/v3/orgs/MSI-Puppet",
    "repos_url": "https://github.umn.edu/api/v3/orgs/MSI-Puppet/repos",
    "events_url": "https://github.umn.edu/api/v3/orgs/MSI-Puppet/events",
    "hooks_url": "https://github.umn.edu/api/v3/orgs/MSI-Puppet/hooks",
    "issues_url": "https://github.umn.edu/api/v3/orgs/MSI-Puppet/issues",
    "members_url": "https://github.umn.edu/api/v3/orgs/MSI-Puppet/members{/member}",
    "public_members_url": "https://github.umn.edu/api/v3/orgs/MSI-Puppet/public_members{/member}",
    "avatar_url": "https://avatars.github.umn.edu/u/10233?",
    "description": null
  },
  "sender": {
    "login": "bert0214",
    "id": 3579,
    "avatar_url": "https://avatars.github.umn.edu/u/3579?",
    "gravatar_id": "",
    "url": "https://github.umn.edu/api/v3/users/bert0214",
    "html_url": "https://github.umn.edu/bert0214",
    "followers_url": "https://github.umn.edu/api/v3/users/bert0214/followers",
    "following_url": "https://github.umn.edu/api/v3/users/bert0214/following{/other_user}",
    "gists_url": "https://github.umn.edu/api/v3/users/bert0214/gists{/gist_id}",
    "starred_url": "https://github.umn.edu/api/v3/users/bert0214/starred{/owner}{/repo}",
    "subscriptions_url": "https://github.umn.edu/api/v3/users/bert0214/subscriptions",
    "organizations_url": "https://github.umn.edu/api/v3/users/bert0214/orgs",
    "repos_url": "https://github.umn.edu/api/v3/users/bert0214/repos",
    "events_url": "https://github.umn.edu/api/v3/users/bert0214/events{/privacy}",
    "received_events_url": "https://github.umn.edu/api/v3/users/bert0214/received_events",
    "type": "User",
    "site_admin": false,
    "ldap_dn": "CN=bert0214,OU=People,DC=ad,DC=umn,DC=edu"
  }
}
```

One of the following paths seems to cause the process to panic:
`$.head_commit.author.username`
`$.head_commit.message`

Note that `head_commit` is null in the json.

Stack trace:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x8450d7]

goroutine 23 [running]:
text/template.errRecover(0xc420119aa8)
        /usr/local/go/src/text/template/exec.go:140 +0x1df
panic(0x8dbc60, 0xc0fa70)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/oliveagle/jsonpath.get_key(0x0, 0x0, 0xc420187681, 0x7, 0x0, 0x7, 0x0, 0x0)
        /local_home/mbaynton/gopath/src/github.com/oliveagle/jsonpath/jsonpath.go:278 +0x67
github.com/oliveagle/jsonpath.JsonPathLookup(0x8d8200, 0xc42022d320, 0xc42013200c, 0x15, 0x8afe00, 0x8afe00, 0xc42011ee01, 0x7f24ca5d76c8)
        /local_home/mbaynton/gopath/src/github.com/oliveagle/jsonpath/jsonpath.go:32 +0x282
github.com/mbaynton/SimplePuppetProvisioner/lib.jsonTemplateGetter.Get(0xc42014d910, 0xc42013200c, 0x15, 0x10, 0xc4201a9c50)

[code calling the library below this point omitted]
```

**Comment by oliveagle** [comment]
done. thx :)
